name: HealthBarIN
version: 1.0
api: [4.0.0, 3.0.0 , 3.0.0ALPHA12]
author: EmeraldYT
description: "Shows Players Heath beside NameTag"
main: HealthTag\HealthTag

commands:
 inhb:
  default: op
  description: "Enables And Disables IN's Health Tag!"
  usage: "/inhb"
